### ISSUE TITLE
Add delete function to list

### ISSUE THREAD

**Issue by DigitalDesignerOnline** [DigitalDesignerOnline/PDF-Uploader#1]
I want to add a checkbox allowing you to delete files within the list using the checkbox within the table.

The file to edit is index.php

**Comment by DigitalDesignerOnline** [comment]
I have now added the form elements just need the delete function added to the mix.

**Comment by waleCloud** [comment]
Hello, if i understand you correctly, you want to be able to delete an uploaded file from your admin area?

If Yes: then you can use the unlink() function of php. like so
`unlink("filePath/name.pdf");`

```
function delete_file($fileName) {
        if(!unlink($fileName)) {
                echo "Sorry! your file cannot be deleted. Please try again later";
        }
        echo "File deleted successfully!";
}
```
to make this work for multiple file deletes, you can add the file names in an array and use a foreach loop to delete the files selected.
``` HTML
<input type='checkbox' name='file_name[]'>
```
``` PHP like so:
foreach($_GET['file_name'] as $fileName){
    // call delete function here.
    delete_file($fileName);
}
```

Hope this helps!

**Comment by DigitalDesignerOnline** [comment]
thanks mate, any chance you can drop that into the index file and shoot a pull request? If not I can fiddle around til it works out lol thanks for the great tip

**Comment by DigitalDesignerOnline** [comment]
the second option is the one I am going to need to work with as the list auto populates the pdf files within its given directory.

**Comment by DigitalDesignerOnline** [comment]
Hi @waleCloud I tried adding your suggestion but the page refreshes to a white screen with the value of the button in the url for some reason. where did I mess up?

**Comment by DigitalDesignerOnline** [comment]
hey @waleCloud getting closer, now it is giving me the error message Sorry! your file cannot be deleted. Please try again later do I need to change file directory permissions or anything like that?

**Comment by waleCloud** [comment]
Oh Yes you need confirm if you have the necessary permissions to access the folders.

use php function ```sh is_readable($filename); ``` to check if you have access to the folder.
if not accessible, try 
```sh 
chmod("/dir/$filename", 0755);
```

if everything doesn't work, make the folders read and write accessible from your server/cpanel.
pr use chmod from this documentation http://php.net/manual/en/function.chmod.php

on a final note, confirm the values of variables your interacting with use ```sh var_dump($variable_name) ```

Hope this is helpful.

**Comment by omarahm3** [comment]
hey @DigitalDesignerOnline I fixed this using get_home_path() to get the absolute path to the file.
I also moved the code that handles the deletion form above it. I tested on my local server and its working perfectly. 
Check my pull request.

**Comment by DigitalDesignerOnline** [comment]
Hey @omarking05  great job mate works like a charm. cant thank you both enough. I will continue enhancing this plugin and am so grateful for the assistance on my first contribution :)

**Comment by omarahm3** [comment]
Wish you all the best, keep it up @DigitalDesignerOnline :)

**Comment by waleCloud** [comment]
Glad you finally figured it out.
Keep building! @DigitalDesignerOnline
